/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufpb.dcx.comerciotech.gui;

/**
 *
 * @author diogo
 */

import br.ufpb.dcx.comerciotech.controller.EstoqueController;
import br.ufpb.dcx.comerciotech.controller.CarrinhoController;

public class MainGUI extends javax.swing.JFrame {
    
    private EstoqueController estoqueController;
    private CarrinhoController carrinhoController;
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        estoqueController = new EstoqueController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        labelImagem = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuEstoque = new javax.swing.JMenu();
        botaoMenuAdicionarProduto = new javax.swing.JMenuItem();
        botaoMenuRemoverProduto = new javax.swing.JMenuItem();
        botaoMenuConsultarPreco = new javax.swing.JMenuItem();
        botaoMenuVerificarDisponibilidade = new javax.swing.JMenuItem();
        botaoMenuGerarRelatorio = new javax.swing.JMenuItem();
        menuCarrinho = new javax.swing.JMenu();
        menuDepartamento = new javax.swing.JMenu();
        menuListar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setPreferredSize(new java.awt.Dimension(1280, 720));

        labelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadoTechLogoMenor.png"))); // NOI18N
        labelImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(labelImagem)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(labelImagem)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        menuEstoque.setText("Estoque");

        botaoMenuAdicionarProduto.setText("Adicionar Produto");
        botaoMenuAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuAdicionarProdutoActionPerformed(evt);
            }
        });
        menuEstoque.add(botaoMenuAdicionarProduto);

        botaoMenuRemoverProduto.setText("Remover Produto");
        botaoMenuRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuRemoverProdutoActionPerformed(evt);
            }
        });
        menuEstoque.add(botaoMenuRemoverProduto);

        botaoMenuConsultarPreco.setText("Consultar preço do Produto");
        botaoMenuConsultarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuConsultarPrecoActionPerformed(evt);
            }
        });
        menuEstoque.add(botaoMenuConsultarPreco);

        botaoMenuVerificarDisponibilidade.setText("Verificar disponibilidade");
        botaoMenuVerificarDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuVerificarDisponibilidadeActionPerformed(evt);
            }
        });
        menuEstoque.add(botaoMenuVerificarDisponibilidade);

        botaoMenuGerarRelatorio.setText("Gerar relatório");
        botaoMenuGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuGerarRelatorioActionPerformed(evt);
            }
        });
        menuEstoque.add(botaoMenuGerarRelatorio);

        barraDeMenu.add(menuEstoque);

        menuCarrinho.setText("Carrinho");
        barraDeMenu.add(menuCarrinho);

        menuDepartamento.setText("Departamento");
        barraDeMenu.add(menuDepartamento);

        menuListar.setText("Listar");
        barraDeMenu.add(menuListar);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuAdicionarProdutoActionPerformed
        estoqueController.adicionarProduto();
    }//GEN-LAST:event_botaoMenuAdicionarProdutoActionPerformed

    private void botaoMenuRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuRemoverProdutoActionPerformed
        estoqueController.removerProduto();
    }//GEN-LAST:event_botaoMenuRemoverProdutoActionPerformed

    private void botaoMenuVerificarDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuVerificarDisponibilidadeActionPerformed
        estoqueController.verificarDisponibilidade();
    }//GEN-LAST:event_botaoMenuVerificarDisponibilidadeActionPerformed

    private void botaoMenuConsultarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuConsultarPrecoActionPerformed
        estoqueController.consultarPrecoDoProduto();
    }//GEN-LAST:event_botaoMenuConsultarPrecoActionPerformed

    private void botaoMenuGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuGerarRelatorioActionPerformed
        estoqueController.gerarRelatorio();
    }//GEN-LAST:event_botaoMenuGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem botaoMenuAdicionarProduto;
    private javax.swing.JMenuItem botaoMenuConsultarPreco;
    private javax.swing.JMenuItem botaoMenuGerarRelatorio;
    private javax.swing.JMenuItem botaoMenuRemoverProduto;
    private javax.swing.JMenuItem botaoMenuVerificarDisponibilidade;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JMenu menuCarrinho;
    private javax.swing.JMenu menuDepartamento;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuListar;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
